version: "3.5"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
